"""add foreign key to Review

Revision ID: 9ef94f37cac2
Revises: 3771d1dcc90f
Create Date: 2024-10-03 15:02:53.986042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef94f37cac2'
down_revision = '3771d1dcc90f'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
#     op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
#     op.drop_column('reviews', 'employee_id')
#     # ### end Alembic commands ###

def upgrade():
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('reviews') as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reviews_employee_id_employees', 'employees', ['employee_id'], ['id'])


def downgrade():
    # Use batch mode for SQLite compatibility in downgrade as well
    with op.batch_alter_table('reviews') as batch_op:
        batch_op.drop_constraint('fk_reviews_employee_id_employees', type_='foreignkey')
        batch_op.drop_column('employee_id')