"""add foreign key to onboarding

Revision ID: d925edff9e3d
Revises: 9ef94f37cac2
Create Date: 2024-10-03 19:24:02.535595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd925edff9e3d'
down_revision = '9ef94f37cac2'
branch_labels = None
depends_on = None

def upgrade():
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('onboardings') as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_onboardings_employee_id_employees', 'employees', ['employee_id'], ['id'])


def downgrade():
    # Use batch mode for SQLite compatibility in downgrade as well
    with op.batch_alter_table('onboardings') as batch_op:
        batch_op.drop_constraint('fk_onboardings_employee_id_employees', type_='foreignkey')
        batch_op.drop_column('employee_id')

# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('onboardings', sa.Column('employee_id', sa.Integer(), nullable=True))
#     op.create_foreign_key(op.f('fk_onboardings_employee_id_employees'), 'onboardings', 'employees', ['employee_id'], ['id'])
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(op.f('fk_onboardings_employee_id_employees'), 'onboardings', type_='foreignkey')
#     op.drop_column('onboardings', 'employee_id')
#     # ### end Alembic commands ###
